export type Agreements={
	title: string;
	url: string;
}

export type AppInfo ={
  name: string;
  version: string;
  logo: string;
  site_url: string;
  agreements: Agreements[];
}

export type GlobalConfig= {
  baseUrl: string;
  appInfo: AppInfo;
}

export const globalConfig  = {
  // baseUrl: 'https://vue.ruoyi.vip/prod-api',
  baseUrl: 'http://localhost:8080',
  // 应用信息
  appInfo: {
    // 应用名称
    name: "ruoyi-app",
    // 应用版本
    version: "1.1.0",
    // 应用logo
    logo: "/static/logo.png",
    // 官方网站
    site_url: "http://ruoyi.vip",
    // 政策协议
    agreements: [{
        title: "隐私政策",
        url: "https://ruoyi.vip/protocol.html"
      },
      {
        title: "用户服务协议",
        url: "https://ruoyi.vip/protocol.html"
      }
    ]
  }
} as GlobalConfig;