import request from '@/utils/request'

// 登录方法
export function login(username:string, password:string, code:string, uuid:string):Promise<UTSJSONObject> {
  const data = {
    username,
    password,
    code,
    uuid
  }
  return request({
    'url': '/login',
    headers: {
      isToken: false
    },
    'method': 'post',
    'data': data
  })
}
export type RegForm={
			username: string,
			password: string,
			confirmPassword: string,
			code: string,
			uuid: string
}
// 注册方法
export function register(data:RegForm):Promise<UTSJSONObject> {
  return request({
    url: '/register',
    headers: {
      isToken: false
    },
    method: 'post',
    data
  })
}

// 获取用户详细信息
export function getInfo():Promise<UTSJSONObject> {
  return request({
    'url': '/getInfo',
    'method': 'get'
  })
}

// 退出方法
export function logout(token?:any):Promise<UTSJSONObject> {
  return request({
    'url': '/logout',
    'method': 'post'
  })
}

// 获取验证码
export function getCodeImg():Promise<UTSJSONObject> {
  return request({
    'url': '/captchaImage',
    headers: {
      isToken: false
    },
    method: 'get',
    timeout: 20000
  })
}
